apiVersion: apps/v1
kind: Deployment
metadata:
  name: tobe-client-deployment 
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: tobe-client
  template:
    metadata:
      labels:
        app: tobe-client
    spec:
      containers:
        - name: container1
          image: danielxburns/tobe-client-k8s-app
          ports:
          - containerPort: 80
          #imagePullPolicy: IfNotPresent #not sure this is necessary. Look it up NOTE 
    