version: '3'
services:
  client:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '80:3000' # verify these NOTE 
    volumes:
      - /app/node_modules
      - .:/app
