sudo: required
services:
  - docker
before_install:
  - docker build -t tobe/client-dev -f client/Dockerfile.dev ./client
script:
  - docker run -e CI=true tobe/client-dev npm run test
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: tobe-list
  env: TobeList-env
  bucket_name: elasticbeanstalk-us-east-2-253737187947
  bucket_path: tobe-list
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
