sudo: required
services:
  - docker
before_install:
  - docker build -t tobe/client-dev -f client/Dockerfile.dev ./client
script:
  - docker run -e CI=true tobe/client-dev npm run test
deploy:
  provider:
