apiVersion: v1
kind: PersistentVolume
metadata: 
  name: tobe-pv 
spec: 
  accessModes:
    - ReadWriteMany
# Verify below is correct NOTE 
  capacity:
    storage: 1Gi #not sure the'i' is needed NOTE 
  hostPath:
    path: /tmp/tobe-pv