apiVersion: v1
kind: Service
metadata:
  name: tobe-backend-service
spec: 
  type: LoadBalancer
  ports:
    - port: 5000 #check the indent here NOTE 
      targetPort: 5000
  selector:
    app: tobe-server-app

